language: julia
julia:
    - 1.1
notifications:
    email: false
include:
    - language: julia
      julia: 1.1
script:
    - make manifest && diff MANIFEST.new MANIFEST
    - make check
    - make data && diff data/utf8proc_data.c.new utf8proc_data.c
    - make clean && git status --ignored --porcelain && test -z "$(git status --ignored --porcelain)"
    - (mkdir build_static && cd build_static && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DUTF8PROC_ENABLE_TESTING=On && make && ctest)
    - (mkdir build_shared && cd build_shared && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=ON -DUTF8PROC_ENABLE_TESTING=On && make && ctest)
